---
- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Update Xorg Config and restart X, Run this whenever you install new GPUs
    command: "{{ item }}"
    become: yes
    with_items:
      - nvidia-xconfig -a --allow-empty-initial-configuration --cool-bits=31 --use-display-device="DFP-0" --connected-monitor="DFP-0"
      - systemctl restart xorg
